ALTER TABLE places
  ADD COLUMN IF NOT EXISTS exact_area TEXT,
  ADD COLUMN IF NOT EXISTS vibe TEXT;

ALTER TABLE experiences
  ADD COLUMN IF NOT EXISTS exact_area TEXT,
  ADD COLUMN IF NOT EXISTS vibe TEXT;
