CREATE TABLE IF NOT EXISTS public.field_research_raw (
  id BIGSERIAL PRIMARY KEY,
  source_row_id TEXT,
  "timestamp" TIMESTAMPTZ,
  place TEXT,
  country TEXT,
  region TEXT,
  neighbourhood TEXT,
  area TEXT,
  area_en TEXT,
  area_fr TEXT,
  short_description TEXT,
  short_description_en TEXT,
  short_description_fr TEXT,
  practical_info TEXT,
  practical_info_en TEXT,
  practical_info_fr TEXT,
  personal_tip TEXT,
  personal_tip_en TEXT,
  personal_tip_fr TEXT,
  why_hidden_gem TEXT,
  traveller_types TEXT,
  child_friendly TEXT,
  best_timing TEXT,
  price_level TEXT,
  google_maps_url TEXT,
  safety_notes TEXT,
  categories TEXT,
  subcategories TEXT,
  vibe TEXT,
  facebook_url TEXT,
  instagram_url TEXT,
  tiktok_url TEXT,
  image_1 TEXT,
  image_2 TEXT,
  image_3 TEXT,
  contact_person TEXT,
  phone TEXT,
  story TEXT,
  story_en TEXT,
  story_fr TEXT,
  transport TEXT,
  entry_type TEXT DEFAULT 'place',
  food_orientation TEXT,
  paid_experience_later TEXT,
  experience_idea TEXT,
  update_notes TEXT,
  translation_source_hash TEXT,
  translation_status TEXT,
  translation_updated_at TIMESTAMPTZ,
  processed BOOLEAN DEFAULT false,
  amenities TEXT
);

ALTER TABLE public.field_research_raw
  ADD COLUMN IF NOT EXISTS source_row_id TEXT,
  ADD COLUMN IF NOT EXISTS "timestamp" TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS place TEXT,
  ADD COLUMN IF NOT EXISTS country TEXT,
  ADD COLUMN IF NOT EXISTS region TEXT,
  ADD COLUMN IF NOT EXISTS neighbourhood TEXT,
  ADD COLUMN IF NOT EXISTS area TEXT,
  ADD COLUMN IF NOT EXISTS area_en TEXT,
  ADD COLUMN IF NOT EXISTS area_fr TEXT,
  ADD COLUMN IF NOT EXISTS short_description TEXT,
  ADD COLUMN IF NOT EXISTS short_description_en TEXT,
  ADD COLUMN IF NOT EXISTS short_description_fr TEXT,
  ADD COLUMN IF NOT EXISTS practical_info TEXT,
  ADD COLUMN IF NOT EXISTS practical_info_en TEXT,
  ADD COLUMN IF NOT EXISTS practical_info_fr TEXT,
  ADD COLUMN IF NOT EXISTS personal_tip TEXT,
  ADD COLUMN IF NOT EXISTS personal_tip_en TEXT,
  ADD COLUMN IF NOT EXISTS personal_tip_fr TEXT,
  ADD COLUMN IF NOT EXISTS why_hidden_gem TEXT,
  ADD COLUMN IF NOT EXISTS traveller_types TEXT,
  ADD COLUMN IF NOT EXISTS child_friendly TEXT,
  ADD COLUMN IF NOT EXISTS best_timing TEXT,
  ADD COLUMN IF NOT EXISTS price_level TEXT,
  ADD COLUMN IF NOT EXISTS google_maps_url TEXT,
  ADD COLUMN IF NOT EXISTS safety_notes TEXT,
  ADD COLUMN IF NOT EXISTS categories TEXT,
  ADD COLUMN IF NOT EXISTS subcategories TEXT,
  ADD COLUMN IF NOT EXISTS vibe TEXT,
  ADD COLUMN IF NOT EXISTS facebook_url TEXT,
  ADD COLUMN IF NOT EXISTS instagram_url TEXT,
  ADD COLUMN IF NOT EXISTS tiktok_url TEXT,
  ADD COLUMN IF NOT EXISTS image_1 TEXT,
  ADD COLUMN IF NOT EXISTS image_2 TEXT,
  ADD COLUMN IF NOT EXISTS image_3 TEXT,
  ADD COLUMN IF NOT EXISTS contact_person TEXT,
  ADD COLUMN IF NOT EXISTS phone TEXT,
  ADD COLUMN IF NOT EXISTS story TEXT,
  ADD COLUMN IF NOT EXISTS story_en TEXT,
  ADD COLUMN IF NOT EXISTS story_fr TEXT,
  ADD COLUMN IF NOT EXISTS transport TEXT,
  ADD COLUMN IF NOT EXISTS entry_type TEXT DEFAULT 'place',
  ADD COLUMN IF NOT EXISTS food_orientation TEXT,
  ADD COLUMN IF NOT EXISTS paid_experience_later TEXT,
  ADD COLUMN IF NOT EXISTS experience_idea TEXT,
  ADD COLUMN IF NOT EXISTS update_notes TEXT,
  ADD COLUMN IF NOT EXISTS translation_source_hash TEXT,
  ADD COLUMN IF NOT EXISTS translation_status TEXT,
  ADD COLUMN IF NOT EXISTS translation_updated_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS processed BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS amenities TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS field_research_raw_source_row_id_unique
  ON public.field_research_raw (source_row_id);
