import { escapeHtml as e } from './sourcesAdminHtml.js';
import { researchSections, researchStatuses, fieldLabel, text, webUrl, fingerprint, signResearchPlan } from './fieldResearch.js';
import { itemHash, itemValues, type ResearchItem, type approvalPreview } from '../data/fieldResearchRepository.js';
export function researchPage(title: string, body: string): string {
    return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(title)} · TUUTI</title><style>
*{box-sizing:border-box}body{margin:0;background:#f2ebd9;color:#102a24;font:16px/1.5 system-ui}header{background:#102a24;color:#fffaf0;padding:18px 5%}a{color:inherit}main{max-width:1180px;margin:30px auto;padding:0 20px}h1,h2{font-family:Georgia,serif;font-weight:500}.panel,.card{background:#fffaf0;border:1px solid #d7d1c1;border-radius:8px;padding:22px;margin:16px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:16px}.card{margin:0}.meta{font-size:13px;color:#647063}.badge{display:inline-block;background:#e5eadc;border-radius:20px;padding:4px 10px}.existing{background:#d9ebdc;color:#174d2b}.possible{background:#fff0ca}.place-matches{border-left:3px solid #9da995;padding-left:12px;margin:14px 0}.new,.in_review{background:#ffe8b0}.error{background:#fbe3dc;padding:14px}.notice{background:#fff0ca;padding:14px}label{display:block;font-weight:600;font-size:14px}input,select,textarea{width:100%;padding:9px;margin:5px 0 12px;border:1px solid #9da995;border-radius:4px;font:inherit}textarea{min-height:100px}input[type=checkbox]{width:auto}.button,button{display:inline-block;background:#102a24;color:#fffaf0;padding:10px 16px;border:0;border-radius:4px;font:inherit;text-decoration:none;cursor:pointer}.actions{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.thumb{width:100%;height:140px;object-fit:cover}.photos img{max-width:240px;max-height:200px}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:13px}table{width:100%;border-collapse:collapse}td,th{padding:10px;border-bottom:1px solid #ddd;text-align:left;vertical-align:top;overflow-wrap:anywhere}.wide{grid-column:1/-1}@media(max-width:650px){table,tbody,tr,td{display:block}thead{display:none}}
</style></head><body><header><a href="/admin">TUUTI Dashboard</a> / <a href="/admin/field-research">Field Research</a></header><main><h1>${e(title)}</h1>${body}</main></body></html>`;
}
const hidden = (name: string, value: unknown) => `<input type="hidden" name="${name}" value="${e(value ?? '')}">`;
const option = (value: string, current: string, label = value) => `<option value="${e(value)}"${value === current ? ' selected' : ''}>${e(label)}</option>`;
const status = (item: ResearchItem) => `<span class="badge ${item.status}">${researchStatuses[item.status]}</span>`;
function existingPlaces(item: ResearchItem): string {
    if (!item.placeMatches) return '';
    if (!item.placeMatches.length) return '<p class="meta">No match found in Places</p>';
    return `<div class="place-matches">${item.placeMatches.map(place => `<p><span class="badge ${place.confirmed ? 'existing' : 'possible'}">${place.confirmed ? '✓ Already in Places' : 'Possible match in Places'}</span><br><a href="/admin/places/${e(place.id)}">${e(place.name)}</a>${place.location ? `<br><span class="meta">${e(place.location)}</span>` : ''}</p>`).join('')}</div>`;
}
function photos(item: ResearchItem): string[] { const values = itemValues(item); return ['image_1', 'image_2', 'image_3'].flatMap(key => text(values[key] ?? item.raw[key]).split(/,\s*(?=https?:)/)).map(webUrl).filter(Boolean); }
function imageUrl(url: string): string { const match = url.match(/drive\.google\.com\/(?:file\/d\/([^/]+)|.*[?&]id=([^&]+))/); return match ? `https://drive.google.com/thumbnail?id=${encodeURIComponent(match[1] ?? match[2])}&sz=w400` : url; }
export function submissionDate(item: ResearchItem): string {
    const raw = text(item.payload.timestamp ?? item.payload.source_timestamp);
    const day = raw.match(/^(\d{1,2})[/-](\d{1,2})[/-](\d{4})/);
    if (day)
        return `${day[3]}-${day[2].padStart(2, '0')}-${day[1].padStart(2, '0')}`;
    return /^\d{4}-\d{2}-\d{2}/.test(raw) ? raw.slice(0, 10) : '';
}
export function renderResearchList(items: ResearchItem[], filters: Record<string, string>, state: Record<string, unknown> | null, csrf: string): string {
    const options = (field: string) => [...new Set(items.flatMap(item => text(itemValues(item)[field]).split(',').map(s => s.trim()).filter(Boolean)))].sort();
    const areas = [...new Set([...options('region'), ...options('neighbourhood')])].sort();
    const filtered = items.filter(item => { const values = itemValues(item); const date = submissionDate(item); return (!filters.q || text(values.place).toLowerCase().includes(filters.q.toLowerCase())) && (!filters.status || item.status === filters.status) && (!filters.area || [values.region, values.neighbourhood].includes(filters.area)) && (!filters.category || text(values.categories).split(',').map(s => s.trim()).includes(filters.category)) && (!filters.from || date >= filters.from) && (!filters.to || Boolean(date) && date <= filters.to); });
    const page = Math.max(1, Number(filters.page) || 1), rows = filtered.slice((page - 1) * 40, page * 40);
    const pageUrl = (number: number) => '/admin/field-research?' + new URLSearchParams({ ...filters, page: String(number) });
    return researchPage('Field Research · Structured Import', `<p>Form → Field Notes → AI → Structured Import → your review → Places</p><div class="panel"><div class="actions">${Object.entries(researchStatuses).map(([key, label]) => `<span class="badge ${key}">${label}: ${items.filter(item => item.status === key).length}</span>`).join('')}</div><p class="meta">Last successful sync: ${e(state?.last_success ?? 'Not yet run')} · ${process.env.FIELD_RESEARCH_AUTOMATION_ENABLED === 'false' ? 'Automatic checks are disabled.' : 'New submissions are checked automatically every minute on staging.'}</p>${state?.error ? `<p class="notice">${e(state.error)}</p>` : ''}<form method="post" action="/admin/field-research/sync">${hidden('_csrf', csrf)}<button>Check for new submissions</button> <a href="/admin/field-research">Refresh overview</a><p class="meta">The check runs in the background. Refresh shortly to see the result.</p></form></div>
 <form class="panel grid" method="get"><label>Place name<input name="q" value="${e(filters.q ?? '')}"></label><label>Status<select name="status">${option('', filters.status, 'All statuses')}${Object.entries(researchStatuses).map(([key, label]) => option(key, filters.status, label)).join('')}</select></label><label>Region / neighbourhood<select name="area">${option('', filters.area, 'All areas')}${areas.map(value => option(value, filters.area)).join('')}</select></label><label>Category<select name="category">${option('', filters.category, 'All categories')}${options('categories').map(value => option(value, filters.category)).join('')}</select></label><label>From<input type="date" name="from" value="${e(filters.from ?? '')}"></label><label>Until<input type="date" name="to" value="${e(filters.to ?? '')}"></label><div class="actions"><button>Filter</button><a href="/admin/field-research">Clear</a></div></form><p>${filtered.length} submissions</p>
 <div class="grid">${rows.map(item => { const v = itemValues(item), photo = photos(item)[0]; return `<article class="card">${photo ? `<img class="thumb" loading="lazy" src="${e(imageUrl(photo))}" alt="Field research photo">` : ''}<h2><a href="/admin/field-research/${item.id}">${e(v.place || 'Untitled submission')}</a></h2>${status(item)}${existingPlaces(item)}<p>${e([v.neighbourhood, v.region].filter(Boolean).join(' · ') || 'Location not yet recorded')}</p><p>${e(v.categories || 'Category not yet recorded')}</p><p class="meta">${e(v.researcher || 'Researcher not recorded')} · ${e(submissionDate(item) || v.timestamp || 'Date not recorded')}<br>${e(item.sourceType)}</p>${item.error ? `<p class="notice">${e(item.error)}</p>` : ''}${item.snapshot && fingerprint(item.snapshot) !== itemHash(item) ? '<p class="notice">Source changed since last review</p>' : ''}</article>`; }).join('') || '<p>No matching submissions.</p>'}</div><p class="actions">${page > 1 ? `<a href="${e(pageUrl(page - 1))}">Previous</a>` : ''}${page * 40 < filtered.length ? `<a href="${e(pageUrl(page + 1))}">Next</a>` : ''}</p>`);
}
function editField(field: string, value: unknown): string {
    const label = e(fieldLabel(field)), content = text(value);
    if (['child_friendly', 'work_friendly'].includes(field)) {
        const normalized = /^(true|yes|oui|ja|1)$/i.test(content) ? 'true' : /^(false|no|non|nee|0)$/i.test(content) ? 'false' : '';
        return `<label>${label}<select name="${field}">${option('', normalized, 'Unknown / not recorded')}${option('true', normalized, 'Yes')}${option('false', normalized, 'No')}</select></label>`;
    }
    const ranges: Record<string, [
        number,
        number
    ]> = { price_level: [1, 5], authenticity: [0, 4], food_orientation: [-2, 2], audience_orientation: [-2, 2], adventure_level: [0, 3], tuuti_pick_level: [0, 3], tuuti_priority: [0, 100] };
    if (ranges[field] && (!content || Number.isInteger(Number(content))))
        return `<label>${label} (${ranges[field].join(' to ')})<input type="number" name="${field}" min="${ranges[field][0]}" max="${ranges[field][1]}" value="${e(content)}"></label>`;
    const multiline = /(description|practical_info|personal_tip|story|notes|field_note|reason|experience_idea)/.test(field);
    return `<label${multiline ? ' class="wide"' : ''}>${label}${multiline ? `<textarea name="${field}">${e(content)}</textarea>` : `<input name="${field}" value="${e(content)}">`}</label>`;
}
export function renderResearchDetail(item: ResearchItem, csrf: string, error?: string): string {
    const values = itemValues(item);
    return researchPage(text(values.place) || 'Review submission', `<p><a href="/admin/field-research">Back to Field Research</a></p>${error ? `<p role="alert" class="error">${e(error)}</p>` : ''}<p>${status(item)} · ${e(values.researcher || 'Researcher not recorded')} · ${e(submissionDate(item) || values.timestamp || 'Date not recorded')}</p>${existingPlaces(item)}<p class="meta">Source: ${e(item.sourceType)} · ${e(item.sourceId ?? item.id)}</p>${item.error ? `<p class="notice">${e(item.error)}</p>` : ''}${item.placeId ? `<p>Previously approved to <a href="/admin/places/${e(item.placeId)}">this Place</a>.</p>` : ''}${item.snapshot && fingerprint(item.snapshot) !== itemHash(item) ? '<p class="notice">The source has changed since the last review. Compare it below before saving.</p>' : ''}
 <form method="post" action="/admin/field-research/${item.id}">${hidden('_csrf', csrf)}${hidden('version', item.version)}${hidden('rawHash', itemHash(item))}
 ${Object.entries(researchSections).map(([title, fields]) => `<section class="panel"><h2>${title}</h2><div class="grid">${fields.filter(field => field in item.payload).map(field => editField(field, values[field])).join('') || '<p class="meta">No separate fields are recorded in this source.</p>'}</div></section>`).join('')}
 <section class="panel photos"><h2>Media · source references</h2>${photos(item).map(url => `<a href="${e(url)}" target="_blank" rel="noreferrer"><img src="${e(imageUrl(url))}" loading="lazy" alt="Field research photo"><br>Open original photo</a>`).join(' ') || '<p>No photos recorded.</p>'}<p class="meta">Photos remain source references. Approval does not change Places photo or video management. Google Drive photos may require permission.</p></section>
 <section class="panel"><label>Review status<select name="status">${Object.entries(researchStatuses).filter(([key]) => key !== 'approved' || item.status === 'approved').map(([key, label]) => option(key, item.status, label)).join('')}</select></label><p class="meta">Saving edits changes only this editorial copy. Approval opens a separate preview before any Place is created or updated.</p><div class="actions"><button name="action" value="save">Save review</button><button name="action" value="preview">Approve / Add to Places</button></div></section></form>
 <details class="panel"><summary>Original submission — read only</summary><pre>${e(JSON.stringify(item.raw, null, 2))}</pre></details><details class="panel"><summary>Original Structured Import / source fields</summary><pre>${e(JSON.stringify(item.payload, null, 2))}</pre></details>`);
}
export function renderResearchMatches(item: ResearchItem, matches: Record<string, unknown>[], csrf: string): string {
    return researchPage('Approve / Add to Places', `<p>${e(itemValues(item).place)} · No place has been changed.</p>${matches.map(place => `<div class="panel"><h2>Possible existing place: ${e(place.name)}</h2><p>${e([place.neighbourhood, place.region, place.status].filter(Boolean).join(' · '))}</p><a class="button" href="/admin/field-research/${item.id}/preview?action=update&amp;placeId=${e(place.id)}">Update existing place — review changes</a></div>`).join('') || '<p>No likely match found.</p>'}<div class="panel actions"><a class="button" href="/admin/field-research/${item.id}/preview?action=create">Create as new place — review changes</a><a href="/admin/field-research/${item.id}">Cancel</a></div><p class="meta">New Places start as drafts. Existing Places are only updated after explicit confirmation.</p>`);
}
export function renderResearchApproval(item: ResearchItem, preview: Awaited<ReturnType<typeof approvalPreview>>, csrf: string): string {
    const { plan, existing, changes } = preview;
    return researchPage(plan.action === 'create' ? 'Confirm new Place' : 'Confirm changes to ' + text(existing?.name), `<p>Review the exact fields below. Missing source fields and media are not copied. Existing publication status and unrelated fields are preserved.</p><form method="post" action="/admin/field-research/${item.id}/approve">${hidden('_csrf', csrf)}${hidden('plan', signResearchPlan(plan))}<div class="panel"><table><thead><tr><th>Apply</th><th>Field</th><th>Current</th><th>Reviewed value</th></tr></thead><tbody>${Object.entries(changes).map(([key, value]) => `<tr><td>${plan.action === 'update' ? `<input type="checkbox" name="fields" value="${key}" checked aria-label="Apply ${e(fieldLabel(key))}">` : 'New'}</td><th>${e(fieldLabel(key))}</th><td><pre>${e(existing?.[key] === undefined ? '—' : JSON.stringify(existing[key]))}</pre></td><td><pre>${e(typeof value === 'string' ? value : JSON.stringify(value))}</pre></td></tr>`).join('')}</tbody></table><label><input type="checkbox" name="confirmed" value="yes" required> I reviewed these changes and approve this submission.</label><div class="actions"><button>${plan.action === 'create' ? 'Approve / Create draft Place' : 'Approve / Update selected fields'}</button><a href="/admin/field-research/${item.id}">Cancel</a></div></div></form>`);
}
