import assert from 'node:assert/strict';
import { emptyEvent, parseEventContext, reviewExtraction, matchEventVenue, validateEvent, screenshotFormat, type ExtractedEvent } from '../src/logic/eventImport.js';
import { newEventDraft, signEventDraft, readEventDraft } from '../src/logic/eventImportDraft.js';
import { renderEventImport, renderEventReview } from '../src/logic/eventsAdminHtml.js';
const blank = parseEventContext({});
const context = parseEventContext({month:'9',year:'2026'});
const fixture: ExtractedEvent = {readable:true,title:'Latine Mix x Afro',venueName:'Prieto',neighbourhood:null,area:null,googleMapsUrl:null,eventDate:'2026-09-19',dateText:'samedi 19',startTime:'20:00',endTime:null,category:'Music',description:'Latin rhythms, Afro vibes, DJ Mirado',price:'Free entry',conditions:'Consumption required',reservationRequired:'unknown',childFriendly:'unknown',contactPhone:'78 731 18 18',instagramAccount:'@prietodakar',recurrence:null,sourceType:'instagram',dateBasis:'provided_context',uncertainFields:[]};
assert.equal(reviewExtraction(fixture,blank).eventDate,null);
const extracted = reviewExtraction(fixture,context);
assert.equal(extracted.eventDate,'2026-09-19');
assert.ok(extracted.uncertainFields.some(f=>f.field==='eventDate'));
assert.equal(extracted.conditions,'Consumption required');
assert.equal(extracted.contactPhone,'78 731 18 18');
assert.equal(reviewExtraction({...fixture,eventDate:'2026-10-19'},parseEventContext({month:'10',year:'2026'})).eventDate,null);
assert.equal(reviewExtraction({...fixture,dateText:'this Saturday'},context).eventDate,null);
assert.equal(reviewExtraction({...fixture,dateText:'September 19, 2026',dateBasis:'explicit'},blank).eventDate,'2026-09-19');
assert.equal(reviewExtraction({...fixture,startTime:'25:00'},context).startTime,null);
assert.throws(()=>reviewExtraction({...fixture,readable:false},context),/readable/);
assert.throws(()=>parseEventContext({month:'13'}));
assert.throws(()=>parseEventContext({publicationDate:'2026-02-30'}));
const venue = {id:'ce286d35-8973-45ef-b0e8-05636e6d7115',name:'Prieto',neighbourhood:'Almadies',area:null};
assert.equal(matchEventVenue('PRIETO',[venue]).exact?.id,venue.id);
assert.equal(matchEventVenue('Prieto',[venue,{...venue,id:'other'}]).exact,null);
assert.equal(matchEventVenue('Absent',[venue]).exact,null);
assert.throws(()=>validateEvent({...emptyEvent(),title:'Party',eventDate:'2026-02-30'}));
assert.throws(()=>validateEvent({...emptyEvent(),title:'Party',sourceUrl:'javascript:alert(1)'}));
assert.equal(validateEvent({...emptyEvent(),title:'Party'}).eventDate,null);
assert.equal(screenshotFormat(Buffer.from([137,80,78,71,13,10,26,10])),'png');
assert.throws(()=>screenshotFormat(Buffer.from('<script>')));
process.env.INBOX_PASSWORD='event-import-test-secret';
const draft=newEventDraft(); draft.context=context; draft.extraction=extracted;
const token=signEventDraft(draft);
assert.deepEqual(readEventDraft(token),draft);
assert.throws(()=>readEventDraft(token+'x'));
assert.throws(()=>readEventDraft(signEventDraft({...draft,expiresAt:1})),/expired/);
const upload=renderEventImport({csrf:'test',cloudinaryReady:true,openaiReady:true});
assert.match(upload,/name="month"/); assert.match(upload,/name="year"/); assert.match(upload,/image\/png/);
const html=renderEventReview({csrf:'test',token,data:{title:'<script>alert(1)</script>'},source:null,extraction:extracted,context,venues:[venue]});
assert.ok(!html.includes('<script>alert(1)</script>'));
assert.match(html,/name="reviewed" value="yes" required/);
assert.match(html,/Consumption required/);
console.log('Event import checks passed: date context, uncertainty, validation, venue matching, source signatures and review form.');

const standalone = validateEvent({...emptyEvent(), title:'Beach party', venueName:'Temporary beach stage', neighbourhood:'Ngor', area:'Dakar', googleMapsUrl:'https://maps.google.com/?q=Ngor', contactPhone:'78 731 18 18'});
assert.equal(standalone.placeId,null);
assert.equal(standalone.neighbourhood,'Ngor');
assert.equal(standalone.area,'Dakar');
assert.equal(standalone.contactPhone,'78 731 18 18');
assert.equal(JSON.parse(JSON.stringify(standalone)).googleMapsUrl,'https://maps.google.com/?q=Ngor');
assert.equal(validateEvent({...standalone,placeId:venue.id}).placeId,venue.id);
assert.throws(()=>validateEvent({...standalone,googleMapsUrl:'javascript:alert(1)'}));
assert.equal(reviewExtraction({...fixture,googleMapsUrl:'javascript:alert(1)'},context).googleMapsUrl,null);
for (const name of ['venueName','neighbourhood','area','googleMapsUrl','contactPhone']) assert.ok(html.includes(`name="${name}"`));
console.log('Standalone and linked event location checks passed.');

assert.equal(validateEvent({...standalone,category:'Workshop',childFriendly:'yes'}).childFriendly,'yes');
assert.equal(validateEvent({...standalone,category:'Workshop'}).childFriendly,'unknown');
assert.throws(()=>validateEvent({...standalone,childFriendly:'maybe'}));
assert.equal(reviewExtraction({...fixture,category:'Workshop',childFriendly:'unknown'},context).childFriendly,'unknown');
assert.equal(reviewExtraction({...fixture,childFriendly:'no'},context).childFriendly,'no');
assert.match(html,/name="childFriendly"/);
console.log('Child-friendly event checks passed.');
