import assert from 'node:assert/strict';
import { emptyEvent, parseEventContext, reviewExtraction, matchEventVenue, validateEvent, screenshotFormat, type ExtractedEvent } from '../src/logic/eventImport.js';
import { newEventDraft, signEventDraft, readEventDraft } from '../src/logic/eventImportDraft.js';
import { renderEventImport, renderEventReview } from '../src/logic/eventsAdminHtml.js';
const blank = parseEventContext({});
const context = parseEventContext({month:'9',year:'2026'});
const fixture: ExtractedEvent = {readable:true,title:'Latine Mix x Afro',venueName:'Prieto',eventDate:'2026-09-19',dateText:'samedi 19',startTime:'20:00',endTime:null,category:'Music',description:'Latin rhythms, Afro vibes, DJ Mirado',price:'Free entry',conditions:'Consumption required',reservationRequired:'unknown',contactPhone:'78 731 18 18',instagramAccount:'@prietodakar',recurrence:null,sourceType:'instagram',dateBasis:'provided_context',uncertainFields:[]};
assert.equal(reviewExtraction(fixture,blank).eventDate,null);
const extracted = reviewExtraction(fixture,context);
assert.equal(extracted.eventDate,'2026-09-19');
assert.ok(extracted.uncertainFields.some(f=>f.field==='eventDate'));
assert.equal(extracted.conditions,'Consumption required');
assert.equal(extracted.contactPhone,'78 731 18 18');
assert.equal(reviewExtraction({...fixture,eventDate:'2026-10-19'},parseEventContext({month:'10',year:'2026'})).eventDate,null);
assert.equal(reviewExtraction({...fixture,dateText:'this Saturday'},context).eventDate,null);
assert.equal(reviewExtraction({...fixture,dateText:'September 19, 2026',dateBasis:'explicit'},blank).eventDate,'2026-09-19');
assert.equal(reviewExtraction({...fixture,startTime:'25:00'},context).startTime,null);
assert.throws(()=>reviewExtraction({...fixture,readable:false},context),/readable/);
assert.throws(()=>parseEventContext({month:'13'}));
assert.throws(()=>parseEventContext({publicationDate:'2026-02-30'}));
const venue = {id:'ce286d35-8973-45ef-b0e8-05636e6d7115',name:'Prieto',neighbourhood:'Almadies',area:null};
assert.equal(matchEventVenue('PRIETO',[venue]).exact?.id,venue.id);
assert.equal(matchEventVenue('Prieto',[venue,{...venue,id:'other'}]).exact,null);
assert.equal(matchEventVenue('Absent',[venue]).exact,null);
assert.throws(()=>validateEvent({...emptyEvent(),title:'Party',eventDate:'2026-02-30'}));
assert.throws(()=>validateEvent({...emptyEvent(),title:'Party',sourceUrl:'javascript:alert(1)'}));
assert.equal(validateEvent({...emptyEvent(),title:'Party'}).eventDate,null);
assert.equal(screenshotFormat(Buffer.from([137,80,78,71,13,10,26,10])),'png');
assert.throws(()=>screenshotFormat(Buffer.from('<script>')));
process.env.INBOX_PASSWORD='event-import-test-secret';
const draft=newEventDraft(); draft.context=context; draft.extraction=extracted;
const token=signEventDraft(draft);
assert.deepEqual(readEventDraft(token),draft);
assert.throws(()=>readEventDraft(token+'x'));
assert.throws(()=>readEventDraft(signEventDraft({...draft,expiresAt:1})),/expired/);
const upload=renderEventImport({csrf:'test',cloudinaryReady:true,openaiReady:true});
assert.match(upload,/name="month"/); assert.match(upload,/name="year"/); assert.match(upload,/image\/png/);
const html=renderEventReview({csrf:'test',token,data:{title:'<script>alert(1)</script>'},source:null,extraction:extracted,context,venues:[venue]});
assert.ok(!html.includes('<script>alert(1)</script>'));
assert.match(html,/name="reviewed" value="yes" required/);
assert.match(html,/Consumption required/);
console.log('Event import checks passed: date context, uncertainty, validation, venue matching, source signatures and review form.');
